#ifndef CBREW_MEMORY_PATCHER_H
#define CBREW_MEMORY_PATCHER_H

#include "AEEStdDef.h"

#include "AEEInterface.h"

#if !defined(AEEINTERFACE_CPLUSPLUS)

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 3/1/2026
//For commercializing this module, please get a valid ClassID.
#define AEECLSID_CBREW_MEMORY_PATCHER 0x00E3782F

#else /* C++ */

#include "AEEStdDef.h"

//WARNING: This classID was locally generated by the wizard 3/1/2026
//For commercializing this module, please get a valid ClassID.
const AEECLSID AEECLSID_CBREW_MEMORY_PATCHER = 0x00E3782F;

#endif /* !defined(AEEINTERFACE_CPLUSPLUS) */

#endif /* #ifndef CBREW_MEMORY_PATCHER_H */
